Fixing build by upgrading dependencies
mediathekview/MServer pull request #652
Opened 2020-12-29 13:52 UTC by Nicklas2751

This should fix the (release) build

What has done?:
- Upgraded all dependencies
- Fixed the generateLicenseReport by using a absolute path

2020-12-29 16:27 UTC, pidoubleyou requested changes
Die MServer-Anpassung reicht leider nicht aus. Für MLib müssen die Abhängigkeiten auch aktualisiert werden, da es okhttp-Funktionen nutzt, die mit der neuen Version entfallen sind.

2020-12-31 00:45 UTC, Nicklas2751 commented
@pidoubleyou Erledigt: https://github.com/mediathekview/MLib/pull/127

2020-12-31 16:29 UTC, pidoubleyou approved these changes
Mit den MLib-Anpassungen läuft der Crawler korrekt 👍

2021-01-01 11:50 UTC, pidoubleyou commented
Ich habe das Problem mit contentLength gelöst:
die Methode `contentLength` liefert die Größe des ResponseBody, der ist bei HEAD-Requests jedoch 0. Deshalb wird wie bisher auch schon der Header `Content-Length` verwendet.

2021-01-12 06:23 UTC, alex1702 commented
@Nicklas2751 Bitte mal angucken warum MLib der release failed (https://github.com/mediathekview/MLib/runs/1674739927?check_suite_focus=true), auch die nightlys failen, wenn ich das richtig sehe.
Vorher kann ich hier nix weiter machen, da MLib fehlt.

2021-01-12 08:11 UTC, merged