Feature/increase test speed
mediathekview/MServer pull request #721
Opened 2021-04-10 13:22 UTC by Nicklas2751

Increased test speed by running tests parallel with maven

Changes:
- MServerConfigManager isn't a singelton anymore
- Using WireMock server non static and with random port
- Replacing all localhost:8589 urls with localhost and current wire mock server port
  - Added helper methods in Mock tools which accepts a function which replaces the Urls
  - Added a method to wiremock test base to replace all "wrong" wire mock urls in an string by the ones with correct port

2021-04-11 13:13 UTC, codingPF commented on src/main/java/de/mediathekview/mserver/crawler/basic/AbstractRecursiveConverterTask.java
> +    config = new MServerConfigManager().getSenderConfig(crawler.getSender());
Kann man hier die config nicht einfach aus dem aCrawler/crawler nehmen?

2021-04-11 13:13 UTC, codingPF commented on src/main/java/de/mediathekview/mserver/crawler/br/tasks/BrGetClipDetailsTask.java
> +    config = new MServerConfigManager().getSenderConfig(crawler.getSender());
Kann man hier die config nicht einfach aus dem crawler nehmen?

2021-04-11 13:18 UTC, codingPF commented on src/test/java/de/mediathekview/mserver/crawler/arte/tasks/ArteSubcategoriesTaskTest.java
> +    System.out.println("Wiremock server url is " + getWireMockBaseUrlSafe());
LOG

2021-04-11 13:20 UTC, codingPF commented on src/main/java/de/mediathekview/mserver/crawler/zdf/tasks/ZdfTaskBase.java
> +          new MServerConfigManager().getSenderConfig(Sender.ZDF).getMaximumRequestsPerSecond());
GGF. die Ratelimiter im crawler verwalten und dann raus geben aber für den Moment nicht wichtig. Sollten wir irgendwann mal angehen...

2021-04-11 13:23 UTC, codingPF requested changes
Commented
Sysout und AbstractRecursiveConverterTask sollte man fixen

2021-04-11 15:46 UTC, pidoubleyou commented on src/test/java/de/mediathekview/mserver/crawler/arte/tasks/ArteSubcategoriesTaskTest.java
> +    System.out.println("Wiremock server url is " + getWireMockBaseUrlSafe());
ich würde die Zeile sogar entfernen. ein Log im UnitTest ist aus meiner Sicht nicht nötig.

2021-04-11 15:55 UTC, pidoubleyou requested changes

2021-04-11 15:55 UTC, pidoubleyou commented on .github/workflows/nightly.yml
> +          maven_args: "--settings .maven.xml -DskipTests"
warum Nightly ohne Tests?

2021-04-11 15:55 UTC, pidoubleyou commented on src/main/java/de/mediathekview/mserver/crawler/arte/tasks/ArteTaskBase.java
> +          new MServerConfigManager().getSenderConfig(Sender.ARTE_DE).getMaximumRequestsPerSecond());
finde ich nicht gut, dass dafür eine neue Instanz angelegt werden muss. aber alle Lösungen, die mir spontan einfallen, machen das ganze nur unnötig kompliziert.

2021-04-11 16:31 UTC, Nicklas2751 commented on .github/workflows/nightly.yml
> +          maven_args: "--settings .maven.xml -DskipTests"
Die Tests laufen bereits im step zuvor. Beim deploy step müssen wir die ja nicht noch ein 2. mal ausführen ;)

2021-04-25 20:14 UTC, Nicklas2751 commented on src/main/java/de/mediathekview/mserver/crawler/arte/tasks/ArteTaskBase.java
> +          new MServerConfigManager().getSenderConfig(Sender.ARTE_DE).getMaximumRequestsPerSecond());
Gefixt durch lazy loading und dort dann die config vom crawler schnappen.

2021-04-25 20:45 UTC, merged